trigger: none

pool: Docker-VM_Pool

stages:
  - stage: TerrafromInitAndValidate
    displayName: Terraform_Init
    jobs: 
    - job: InitAndValidate
      displayName: InitAndValidate
      steps:
      - task: TerraformInstaller@1
        inputs:
          terraformVersion: 'latest'
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'init'
          backendServiceArm: 'Axion-Service-Connection'
          backendAzureRmResourceGroupName: 'Backend_RG'
          backendAzureRmStorageAccountName: 'axionstatestorage'
          backendAzureRmContainerName: 'axioncontainer'
          backendAzureRmKey: 'terraform.tfstate'
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'validate'
  - stage: Scanning
    displayName: Terraform_Code_Scanning
    dependsOn: TerrafromInitAndValidate
    condition: succeeded()
    jobs:
    - job: Code_Scanning
      displayName: Code_Scanning
      continueOnError: true
      steps:
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash
            
            tfsec .
          workingDirectory: '$(System.DefaultWorkingDirectory)'

      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            cd $(System.DefaultWorkingDirectory)
            tflint --init
            tflint --recursive -f default
        displayName: 'Run tfsec'
        continueOnError: true
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: 'checkov -d'
          workingDirectory: '$(System.DefaultWorkingDirectory)'
        displayName: 'Run Checkov'
        continueOnError: true
      



      

      
        
      
