name: Container Registry - Deployment
description: Request deployment of an Azure Container Registry.
title: "Container Registry - Deployment"
labels:
  - create-azure-container-registry

body:
  - type: markdown
    attributes:
      value: |
        ### Azure Container Registry - Deployment
        Fill in the fields below to deploy an Azure Web App via the automation pipeline.
        Execution starts when this issue gets the label **create-azure-container-registry**.
        
  - type: input
    id: ritm
    attributes:
      label: ritm
      description: "RITM number for audit traceability. Example: RITM1234567"
      placeholder: RITM1234567
      value: RITM1234567
    validations:
      required: true
  
  - type: dropdown
    id: dso
    attributes:
      label: dso
      description: DSO / operational ownership for this Logic App.
      options:
        - FAAST
        - WIPRO
        - CTS
        - DXC
        - TCS
      default: 0
    validations:
      required: true

  - type: dropdown
    id: subscription_id
    attributes:
      label: subscription_id
      description: "Select subscription from the given list."
      options:
        - FAAST NON-PROD
        - FAAST PROD
        - Data & Analytics PaaS Non-Prod
        - Data & Analytics PaaS Prod
      default: 0

  - type: input
    id: resource_group_name
    attributes:
      label: resource_group_name
      description: "Must already exist in the selected subscription."
      placeholder: AZ26P1-APP-RG01
      value: AZ26P1-APP-RG01
    validations:
      required: true

  