name: Container Registry - Deployment
description: Request deployment of an Azure Container Registry.
title: "Container Registry - Deployment"
labels:
  - create-azure-container-registry

body:
  - type: markdown
    attributes:
      value: |
        ### Azure Container Registry - Deployment
        Fill in the fields below to deploy an Azure Web App via the automation pipeline.
        Execution starts when this issue gets the label **create-azure-container-registry**.
        
  - type: input
    id: ritm
    attributes:
      label: ritm
      description: "RITM number for audit traceability. Example: RITM1234567"
      placeholder: RITM1234567
      value: RITM1234567
    validations:
      required: true
  
  

    id: network_connectivity
    attributes:
    label: Network Connectivity
    description: Select the approved network
    options:
    - Public access
    - Private access
  
